### ISSUE TITLE
CMS strategy

### ISSUE THREAD

**Issue by chriscoyier** [chriscoyier/coding-fonts#4]
There is a whole big list of fonts (see current README). Each font has a variety of metadata:

- Name
- Designer(s)
- URL to some kind of homepage for it
- Some kind of description maybe?

Then of course the screenshots of the samples. 

Seems like a job for Markdown files with Frontmatter and Eleventy to me.

**Comment by landjonathan** [comment]
+1 for Markdown + Eleventy. 
Is the plan ultimately to include all the font files in the repo? Or to just create the screenshots locally and add them? 
It would be cool for the screenshots to be created in CI/CD, but unless the samples change often, it might be too much of a hassle. Not to mention licensing issues.

**Comment by landjonathan** [comment]
Yeah, very tricky indeed. For the sake of clirity, maybe the website should separate fonts by licence, like in the repo's readme.

**Comment by chriscoyier** [comment]
Sure yeah we could categorize them by license. That would be good metadata to include, and also price. Ligatures is also great metadata to have. Some people feel the exact opposite of you also, so it's useful information on both sides.

**Comment by chriscoyier** [comment]
```
---
layout: font
title: Fira Code
home_url: https://github.com/tonsky/FiraCode
license: 
  - name: OFL-1.1 License
     url: https://github.com/tonsky/FiraCode/blob/master/LICENSE
cost: free
support: 
  - name: Patreon
     url: https://www.patreon.com/tonsky
  - name: GitHub Sponsors
     url: https://github.com/sponsors/tonsky
ligatures: optional
---

Not sure we we should include some kind of blockquote description or something? Might be tough to get right.

```

Maybe we don't need to include links to the images because that's assumed somehow? Or maybe we should be explicit?
